### ISSUE TITLE
rescan from seed missing addresses

### ISSUE THREAD

**Issue by Erovyr101** [decred/dcrwallet#106]
It could be related to a similar issue posted recently but when recreating a wallet from seed and syncing to the most recent block  not all addresses are accounted for and scanned.

For example my wallet currently have 1400+ addresses from pos and pow mining but when I recreate the wallet it will only detect and scan around 1200 or so, thus funds appears to be missing. I don't see a way at the moment to easily force a rescan of the missing addresses.

**Comment by cjepson** [comment]
You're the second user to report this with a very large wallet. Can you e-mail me the extended pubkey (getmasterpubkey) so I can try to sync it locally and reproduce? cjepson@decred.org

**Comment by chappjc** [comment]
My last rebuild from seed scanned for 2020 addresses, so this is alarming.  How do I know how many addresses my wallet has used vs scanned for?

**Comment by cjepson** [comment]
By iteratively scanning addresses at an index with existsaddress. There is no good functionality in wallet to get an address at an index. I hope to have some more additions to the RPC soon to fix this.

**Comment by jrick** [comment]
It is possible to get the number of keys in each account: https://gist.github.com/jrick/615a252b004ea0220145

That information is currently only exposed in the new RPC API, but it's there.

**Comment by chappjc** [comment]
@jrick Let me see if I understand.  The suggested process is to fetch the key count using the gist on the present wallet that was rebuild from seed, then unarchive and start your wallet backup created before you recreated from seed, then fetch that key count and compare?

But does the key count on the previous wallet include all addresses that were generated, **even if they were not used**?  Because to then determine if used addresses are missing from the rebuilt wallet, the key count on the rebuilt wallet must include them too.  I don't understand the scanning process, obviously.

If a future code change followed by rebuild from seed can correctly recover all addresses, then I'll just relax.  :)

**Comment by jrick** [comment]
@chappjc that comment was more aimed towards @cjepson in case she wanted to inspect the number of addresses in each account before and after, but feel free to play around and test it as well if you want.  Yes, the correct way to do that would be to check the number of addresses from an original wallet, recover it from the seed, and then check again in the new wallet.

You're also right that the counts should be the same regardless of whether the addresses were used or not.  If an account has 2 addresses, with the first unused and the second used, it still has to generate 2 addresses in order to derive that second address.  Therefore, after recovery, the total address could should be 2.

**Comment by jrick** [comment]
Do these wallets that are experiencing these issues use accounts other than the default account?

**Comment by Erovyr101** [comment]
In my case, I only have the default account.

**Comment by cjepson** [comment]
@chappjc If you load wallet with debug (-d debug) it will print the default account address indexes. You can check there to ensure that restoring a wallet from seed functions correctly.

**Comment by jcvernaleo** [comment]
@cjepson and @chappjc was this fixed by #121 ?

**Comment by cjepson** [comment]
Yes can be close

**Comment by chappjc** [comment]
There is [a report](https://forum.decred.org/threads/dd-4-v0-0-8-03-18-16.1336/page-3#post-15010) that this issue is still occurring in 0.0.8.

**Comment by Erovyr101** [comment]
With 0.0.8  the re-scan of my wallet from seed find  1520 addresses.  On my original wallet  there is 1522.  However my balance is now consistent between the two. I assume the 2 missing addresses are  empty and irrelevant.

I also confirmed the number of addresses on linux for the 2 wallet files with the command
dcrctl --wallet listreceivedbyaddress | grep address | wc -l

**Comment by Stradivario** [comment]
Hello guys i have the same problem with my seed first i have some TYPING miss take inside my Decred Seed which is not from my side but instead the system before 5 months decided to not confirm my seed and throws error INVALID seed from more research i found TYPO miss take in my seed which is not from my side because i COPY and PASTE the seed from wallet.decred.org to my TEXT document.I think nobody wants to change typo miss take inside WALLET SEED.
So ok i import my wallet it recognize it with new TYPO added but there is no funds inside the wallet hm... it strange i have 1.7 Decred inside this wallet and when i look at my account inside https://www2.coinmine.pl my Payment address is set DsVK1vLvxkc59iN6hUpNye1wSMqBDwjVRHr and inside of it there is a 1.7 decred's https://mainnet.decred.org/address/DsVK1vLvxkc59iN6hUpNye1wSMqBDwjVRHr
So somehow my SEED forgot about this Generated wallet address and now i cannot see my 1.7 decred balance inside my wallet....

Of course i try Settings Rescan Wallets for funds nothing happen so is there any chance that i can get my small amount 1.7 Decred back to my wallet ? 

Thank you in advance.

Best Regards,
Kristiyan Tachev
